export const SET_LOADED_FILE = 'SET_LOADED_FILE'

export const SET_LABELING_MODE = 'SET_LABELING_MODE'

export const SET_ERASER_RADIUS = 'SET_ERASER_RADIUS'

export const SET_BRUSH_RADIUS = 'SET_BRUSH_RADIUS'

export const UP_BRUSH_RADIUS = 'UP_BRUSH_RADIUS'

export const DOWN_BRUSH_RADIUS = 'DOWN_BRUSH_RADIUS'

export const SET_BRUSH_COLOR = 'SET_BRUSH_COLOR'

export const SELECT_MENU = 'SELECT_MENU'

export const SHOW_SAVE_POPUP = 'SHOW_SAVE_POPUP'





export const EXPAND_MENU = 'EXPAND_MENU'

export const SELECT_CANVAS = 'SELECT_CANVAS'

export const SET_SHOW_TAGS = 'SET_SHOW_TAGS'

export const SHOW_TAGS_MENU_TOGGLE = 'SHOW_TAGS_MENU_TOGGLE'

export const SEGMENTATION_VISIBLE_TOGGLE = 'SEGMENTATION_VISIBLE_TOGGLE'

export const SEGMENTATION_SELECTED_TOGGLE = 'SEGMENTATION_SELECTED_TOGGLE'
