export const MENU_CLICKED = 'MENU_CLICKED'

export const FILE_UPLOADED = 'FILE_UPLOADED'

export const SHOW_BRUSH_POPUP = 'SHOW_BRUSH_POPUP'

export const SHOW_ERASER_POPUP = 'SHOW_ERASER_POPUP'

export const SHOW_SAVE_POPUP = 'SHOW_SAVE_POPUP'

export const SHOW_HELP_POPUP = 'SHOW_HELP_POPUP'

export const SAVE_FILE = 'SAVE_FILE'





export const FILE_UPLOADED_SEG = 'FILE_UPLOADED_SEG'

export const SHOW_SEGMENTATION_POPUP = 'SHOW_SEGMENTATION_POPUP'

export const SHOW_ANALYSIS_REPORT_POPUP = 'SHOW_ANALYSIS_REPORT_POPUP'
